### ISSUE TITLE
!theme returns current theme twice

### ISSUE THREAD

**Issue by cmjchrisjones** [MichaelJolley/vscode-twitch-themer#66]
When issuing the `!theme` command, its currently returning the current theme twice.

[Twitch Clip showing the issue](https://clips.twitch.tv/RealRespectfulKangarooMingLee)

**Comment by MichaelJolley** [comment]
@cmjchrisjones, it was mentioned in the last stream that this may be due to the fact that I've got code open in two windows.  One is normally our stream notes off screen and the other is on stream that everyone sees.  I'll bet both are connected and responding to requests.  Let's test this out on tomorrows stream.  I'll open the show notes in notepad or something and keep one editor open.

**Comment by MichaelJolley** [comment]
@all-contributors please add @cmjchrisjones for bugs

**Comment by MichaelJolley** [comment]
Can confirm that this was due to having twitch themer connected in two instances of code.  Closing this one out.
